### PR TITLE
Implementation of Admin dashboard nav bar

### LINKED ISSUE #78: Feat: implementation of Dashboard nav bar
### Description:
-As an admin, I need a dashboard see updates by managing orders, sellers, customers, and products component. This involves implementing and creating a responsive dashboard nav bar where admin were redirected because of his role and writing unit tests to ensure functionality and reliability.

#### Navbar for Dashboard:
- [ ] Implement reusable navbar component for both desktop and mobile devices
- [ ] writing unit tests to ensure functionality and reliability.
### Definition of Done

- The dashboard nav bar  is implemented and styled according to design.
- Unit tests are written and passing

### PR DESCRIPTION
**Pull request by Dawaic6**
## What does this PR do?
This PR implements a responsive dashboard navbar for the application, specifically designed for admin users to manage orders, sellers, customers, and products. The implementation includes creating a reusable navbar component that adapts seamlessly to both desktop and mobile devices, and writing unit tests to ensure functionality and reliability.

### Components:

- **DashNavbar:** The main component that serves as the dashboard navbar, providing navigation options for admins.
- **ProfileMenu:** A dropdown menu for profile-related actions, including editing the profile, accessing preferences, toggling night mode, and signing out.
### Interactivity: 
- **Profile Menu Toggle:** A function to toggle the visibility of the profile menu when the avatar is clicked.
### Styling:

- **Responsive Design:** Tailwind CSS classes are applied to ensure the navbar is responsive and looks consistent across different devices, including mobile, tablet, and desktop.

## Screenshots:
**Tests Screenshot**
image

**UI on Mobile**
image

**UI on Desktop**
image

### Checkout this branch and run the application:

- Ensure that the dashboard navbar matches the provided design specifications.
- Test the navbar on different screen sizes to verify responsiveness.
- Click on the profile avatar and check that the profile menu expands/collapses correctly.
- Review the code for clarity, adherence to best practices, and compliance with project guidelines.
### Run the unit tests:
- Verify that all tests pass and that they cover rendering, interactivity, and data flow aspects.

## Description of the tasks completed:

- Implement the dashboard navbar component.
- Write appropriate tests for rendering and interactivity.
- Ensure components are styled and responsive.

### CODE REVIEW

**Review by jkarenzi — COMMENTED** [review]
- The navbar on mobile devices looks a bit cluttered.
- The menu icon also appears to have a shadow

**Review by EddyShimwa — APPROVED** [review]

**Review by niyibi250 — COMMENTED** [review]
make sure the outlet takes the remaining space not overlapping with the DashboardSideNav that make using you layout impossible

**Review by ambroisegithub — APPROVED** [review]
I looks good for merge!!!

**Review by 13XAVI — APPROVED** [review]
Nice

**Review by niyibi250 — APPROVED** [review]

**Review by jkarenzi — APPROVED** [review]

**Review by dushimeemma — APPROVED** [review]

**Pull request merged**
