### PR TITLE
Implement Role-Based Access Control

### LINKED ISSUE #89: Implement User Role Functionalities
## Description:
 Implement the user role functionalities as shown on figure below. This feature will include adding, editing, and deleting user roles, as well as displaying a list of existing roles.

#### provided design 
Screenshot 2024-07-10 at 17 33 13

## Tasks

1. **Create the User Role Side Bar Item **

- Add a new item named "User Role" in the sidebar.
- Ensure it has sub-items: "All Role" and "Add New".

2. **Design the User Roles Page**

- **User Role List**

 - Display a table with the following columns: ID, Role Name, and Action.
 - Actions should include Edit and Delete icons.

- **Register Role Form**

  -   Include input fields for Role Name and Role ID.
  - Add a button to submit the new role.
 
3. **Implement the User Role Functionalities**

- **Add New Role**

   - Implement form submission to create a new role.
   - Validate the input fields.

- **Edit Role**

   - Implement the edit functionality for existing roles.
   - Pre-fill the form with the role's current data.
- **Delete Role**

  -  Implement the delete functionality to remove a role.
  - Add a confirmation dialog before deletion.
4. **Backend Integration**

- Connect the frontend with the backend API to fetch, add, edit, and delete roles.
5. **Testing**
- Write unit and integration tests to ensure all functionalities work as expected.
## Definition of Done

- A fully functional User Roles : add, edit, and delete functionalities.
- A responsive UI matching the provided design.
- Integration with the backend API for role management.
- Comprehensive unit and integration tests ensuring all functionalities work as expected.

### PR DESCRIPTION
**Pull request by ambroisegithub**
This PR adds role-based access control (RBAC) to the frontend of the project, allowing for fine-grained access management based on user roles.

### **Tasks Completed:**

- [x] Defined roles and permissions for vendors, buyers, and admins.
- [x] Integrated an API endpoint for managing roles and permissions.
- [x] Enforced role-based access control throughout the frontend application.
- [x] Implemented appropriate error handling and user feedback for access control issues.
- [x] Added comprehensive unit tests for the RBAC implementation.
### **How to Test:**

- Clone the repository and set up the development environment.
- Perform CRUD operations on roles by interacting with the /api/v1/roles route via the frontend interface.
- Test the checkRole and checkPermissions middleware by accessing routes that require specific roles and permissions.
- Verify that users with different roles see the appropriate UI elements and have access to the correct features.
### **Context:**
- There are three roles: Vendor, Buyer, and Admin.

### **Vendor Permissions:**

- Manage Products
- Fulfill Orders
- View Sales Reports
- Manage Inventory
- Manage Account
### **Buyer Permissions:**

- Browse Products
- Add to Cart
- Check Out
-  Order History
- Track Orders
- Manage Account
- Leave Reviews
- View Wishlist
- Receive Notifications
### **Admin Permissions:**

- Manage Users
- Manage Roles
- Manage Products
- Manage Orders
- Manage Categories
- Manage Shipping
- Manage Payments

### CODE REVIEW

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 10-37-07
Screenshot from 2024-07-25 10-37-56

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 10-37-56

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 11-03-29

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 11-01-45

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-19 13-33-10

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-19 13-34-03

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 11-01-45

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 11-02-32
Screenshot from 2024-07-25 11-03-29

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 11-22-17
Screenshot from 2024-07-25 11-03-29

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 11-08-53

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 11-09-46

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 11-09-46

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 11-10-03

**Comment by ambroisegithub** [comment]
Screenshot from 2024-07-25 11-13-42

Screenshot from 2024-07-25 11-12-15

**Review by 13XAVI — APPROVED** [review]

**Review by jkarenzi — APPROVED** [review]

**Review by Dawaic6 — APPROVED** [review]

**Review by niyibi250 — APPROVED** [review]

**Review by dushimeemma — APPROVED** [review]

**Pull request merged**
