### PR TITLE
#14 Write project readme file

### LINKED ISSUE #14: Write detailed README
#### Description
As a developer, I want to create a comprehensive README file for the e-commerce project, providing crucial information about the project, its setup, and its status. Additionally, I want to add relevant badges to the README to display important project metrics and build statuses at a glance.

A well-written README file and informative badges will help new contributors and stakeholders understand the project quickly and make it easier to collaborate and contribute effectively.

#### Tasks
- [ ] Create an appealing README file
- [ ] Include project description, installation instructions, and usage examples
- [ ] Add badges for build status, test coverage, and code quality

#### Related issues
- #1

#### Definition of Done
- README file is appealing
- README file includes project description, installation instructions, and usage examples
- README file contains badges for build status, test coverage, and code quality

### PR DESCRIPTION
**Pull request by jkarenzi**
####  What does this PR do?

This PR adds a well-written README file and informative badges that will help new contributors and stakeholders understand the project quickly and make it easier to collaborate and contribute effectively.

#### Description of the tasks to be completed

- [x] Create an appealing README file
- [x] Include project description, installation instructions, and usage examples
- [ ] Add badges for build status, test coverage, and code quality

#### How can this be manually tested?
- By previewing the readme file in vscode or taking a look at it in the root directory of the dynamites-ecomm-fe repo.

#### What are the relevant pivotal trackers/story id?
- #14

### CODE REVIEW

**Review by ambroisegithub — APPROVED** [review]
It Looks super for merging!!!

**Review by Dawaic6 — APPROVED** [review]

**Review by wayneleon1 — APPROVED** [review]
Good Job

**Review by EddyShimwa — APPROVED** [review]
Good Job!

**Review by dushimeemma — APPROVED** [review]
Good job @jkarenzi 🥇

**Pull request merged**
